### ISSUE TITLE
How to install Depencies

### ISSUE THREAD

**Issue by imsamimalik** [sign-language-processing/pose-to-video#1]
`pip install .[pix2pix]` how do you this command? Because it is not a normal pip command neither the project toml file is a **poetry** file. Which python packager manager are you using?

**Comment by AmitMY** [comment]
That is a normal pip command that installs this line 
https://github.com/sign-language-processing/pose-to-video/blob/main/pyproject.toml#L24

**Comment by imsamimalik** [comment]
when I try to install it on my Ubuntu setup, it says `zsh: no matches found: .[pix2pix]`

![image](https://github.com/sign-language-processing/pose-to-video/assets/42075879/89141a7e-97ab-43bc-ae5f-b74314c056fc)

**Comment by AmitMY** [comment]
The error message zsh: no matches found: .[pix2pix] indicates that zsh (the Z Shell) is trying to interpret the square brackets [ ] as a pattern-matching glob (similar to wildcard characters like *), but can't find any files that match this pattern. This is a common issue with zsh and other shells that have their own globbing or pattern matching features.

Instead, use `pip install '.[pix2pix]'` (https://github.com/sign-language-processing/pose-to-video/commit/68caf794dbf2385b1a535e63460a9c1a624fcb47)

**Comment by imsamimalik** [comment]
Thanks for the clarification.
