### ISSUE TITLE
Avatar customization possible?

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/pose-to-video#6]
Dear @AmitMY  Is it possible to replace the avatar with any other? as I have used in sign translation and I couldn't figure out if any other still avatar can be included on fly? or do I have to retrain engine completely with changed desired avatar? Please if you could guide.

**Comment by AmitMY** [comment]
For the `pix2pix` model, for example, you have to retrain.
For the `controlnet` model, you can just give a text prompt (for example, "a black man"), but performance not gurenteed.
For the `animatediff` post-processor, you can also specify the prompt.

In my opinion, for good quality, you should use `controlnet` as is, then, in the `animatediff`, specify a different person. If it doesn't change *enough*, you can give the animatediff more diffusion steps.

**Comment by Tortoise17** [comment]
Is it possible to export video with only pose without any human ? using controlnet? if you can guide that way also.?

**Comment by AmitMY** [comment]
From https://github.com/sign-language-processing/pose, the following command will visualize the pose:
```bash
visualize_pose -i file.pose -o file.mp4
```

If you wanted to edit the prompt, you have to change it in the code, locally, then run this command.
It was not designed to make the prompt changeable. One can add that if you find it useful with different prompts

**Comment by Tortoise17** [comment]
Great help. Thank you. I will try to implement the prompt stuff if successful.
